# Generated by Django 5.1.5 on 2025-01-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(null=True),
        ),
    ]
